syntax on
set number
set autoindent
set smartindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set hlsearch
set updatetime=100
set noswapfile
set foldmethod=indent
set encoding=utf8
set foldlevelstart=20
set undodir=~/.vim/undodir
set undofile
